### PR TITLE
Fix linter issues blocking build

### PR DESCRIPTION
**Pull request by VanAnderson**
This PR fixes some linter issues that were blocking local builds.

### CODE REVIEW

**Review by T-Hugs — APPROVED** [review]
Thanks for the fixes!

**Comment by T-Hugs** [comment]
cc @dgreif

**Comment by dgreif** [comment]
@VanAnderson you shouldn't need to change anything with lint since it's passing in CI.  I _did_ update some of the eslint dependencies, so verify you are up to date locally

**Review by dgreif — APPROVED** [review]
Sorry for the trouble!

**Pull request merged**
