### PR TITLE
fix: npm ignore __tests__ & stories

### PR DESCRIPTION
**Pull request by andykenward**
When compiling `dist:transpile:cjs` or `dist:transpile:esm` babel is including the folders `__tests__` & `stories` in the output. But we don't want to publish those files to npm. Adding those folders to ignore in the `package.json` `files` array should solve this.

### CODE REVIEW

**Comment by colebemis** [comment]
Thanks for the PR, @andykenward ❤️  Could you elaborate on what you mean by "dist:types is generating type definitions for the same folders"?

**Comment by andykenward** [comment]
Sorry, I deleted the scripts `dist:types` by mistake.

But I mean't that when you run `yarn dist:types` it generates TypeScript definitions for the `__tests__` & `stories` folders. Which seems pointless.

CleanShot 2021-04-16 at 19 29 17@2x
CleanShot 2021-04-16 at 19 29 47@2x

**Comment by colebemis** [comment]
Ah, I see. We do want to type check the tests and the stories but we ignore those files when publishing to npm: https://github.com/primer/components/blob/3af005c6ec7d0900cc46728d5c725887bf7ba57c/package.json#L41-L42

**Comment by andykenward** [comment]
> Ah, I see. We do want to type check the tests and the stories but we ignore those files when publishing to npm:
> 
> https://github.com/primer/components/blob/3af005c6ec7d0900cc46728d5c725887bf7ba57c/package.json#L41-L42

Perhaps also add the compiled `stories` folder to be ignored too, as this is only for storybookjs? 

```json
 "!lib/stories", 
 "!lib-esm/stories" 
```

**Comment by colebemis** [comment]
@andykenward Great idea!

**Comment by andykenward** [comment]
@colebemis Sorry in the delay in this pull request. I've made the discussed changes.

**Review by colebemis — APPROVED** [review]
🚀

**Pull request merged**
