### PR TITLE
publish to GPR as well as NPM! 💕🙌

### PR DESCRIPTION
**Pull request by emplums**
Updates our main.workflow to publish to GPR as well as npm :)

This is currently working with the stock npm Action, I want to make it work with primer/publish before merging so we can use canary publishes, etc :)

### CODE REVIEW

**Comment by emplums** [comment]
@shawnbot yep that's the idea!

**Comment by erictuvesson** [comment]
Hey, any updates on this? 😃

**Comment by emplums** [comment]
Closing for now as this isn't a super high priority and this branch is super stale at this point!

**Comment by pqt** [comment]
@erictuvesson I was subscribed to this PR just to see how it went, if you actually just run NPM publish to GPR after primer publish has happened, everything seems to work(ish) as intended with the right versions.

I did it here and it's kind of limping along so I'm happy enough with it for the time being 😂 https://github.com/paquette/react-components/blob/master/.github/workflows/main.yml

**Pull request closed without merging**
