### PR TITLE
Update intro/getting started docs

### PR DESCRIPTION
**Pull request by BinaryMuse**
This PR fixes a couple issues with the docs:

* The Getting Started page is hard to find as the link is the heading and the heading has no visible indication of being clickable
* The index page (linked to from the Components heading) duplicates a lot of this info but the two pages have drifted out of date over time.

In this PR, I've combined the two pages and made it the index page, and changed the left nav so that a "Getting Started" page appears in the nav; this redirects to the index page and I've set up a now redirect to handle the change.

This also includes the changes from #785 

Demo: https://primer-components-git-mkt-some-docs-updates.primer.now.sh/components/

### CODE REVIEW

**Comment by emplums** [comment]
Hey! It looks like by merging the index page, About link, and Getting Started page, we lose the hero image and some of the content that was originally in the index. 

I think we should just merge `About` and `Getting Started` and keep the index page as is with the hero and a little intro, but maybe remove some of the content that's also in `Getting Started` and just link to the getting started docs on that page? So the index page would essentially be: hero image, `What are Primer Components?`, `Principles` and maybe `Local Development`?

**Comment by BinaryMuse** [comment]
> Hey! It looks like by merging the index page, About link, and Getting Started page, we lose the hero image and some of the content that was originally in the index.

Ah I totally missed the hero image, that was my fault. But let it be known that I really dislike our hero image; it takes up almost the entire screen for me. (But that's a different discussion :)

image

> I think we should just merge `About` and `Getting Started` and keep the index page as is

What are you referring to when you mention `About`? I only merged two pages (getting started and index).

**Comment by BinaryMuse** [comment]
Oh wait, it's the new heading I added 🙈 

So do you think the Components subheading should still link to the index page, and have some of the original content (and hero image) and the About Link and Getting Started page should lead to the same page (with installation instructions and such)?

**Comment by BinaryMuse** [comment]
I added the Hero and the stuff I missed copying over; still think it needs to be two pages? I'm not exactly sure where to link to them from given the subheadings are suboptimal.

**Comment by emplums** [comment]
This is what I had in mind:

Index:
- Hero image
- Intro
- Principles
- Local development (heads up the markdown heading is currently broken just for this heading for some reason 🤔, it's just showing the hashes instead of turning it into a heading )

About:
- redirects to Getting Started
- Doesn't have a hero image

Getting Started:
- no hero image
- has all the getting started docs
- doesn't include intro/principles/local development

**Comment by BinaryMuse** [comment]
Gotcha. Do you think the index page should still be linked to from the Components subheader?

**Pull request merged**
