### PR TITLE
Drop babel polyfills

### PR DESCRIPTION
**Pull request by keithamus**
### What?

This PR does a few things, but all to achieve one goal; removing Babel runtime imports from the output build. You can read the individual commits to get an idea of the individual parts, but largely:

 - Reconfigure Babel to remove the runtime/env plugins
 - Add in the `nullish-coalescing-operator` proposal plugin which is implicitly part of env
 - Upgrade Rollup and tweak the config.

### Why?

The `babel/runtime` package includes runtime functions which can be used to "ponyfill" certain features in the web platform. 

We can see which features we're relying on:

```
rg babel lib-esm/ -I | sort | uniq
import _asyncToGenerator from "@babel/runtime/helpers/asyncToGenerator";
import 'babel-polyfill';
import _classCallCheck from "@babel/runtime/helpers/classCallCheck";
import _createClass from "@babel/runtime/helpers/createClass";
import _createForOfIteratorHelper from "@babel/runtime/helpers/createForOfIteratorHelper";
import _defineProperty from "@babel/runtime/helpers/defineProperty";
import _extends from "@babel/runtime/helpers/extends";
import _objectSpread from "@babel/runtime/helpers/objectSpread2";
import _objectWithoutProperties from "@babel/runtime/helpers/objectWithoutProperties";
import _regeneratorRuntime from "@babel/runtime/regenerator";
import _slicedToArray from "@babel/runtime/helpers/slicedToArray";
import _taggedTemplateLiteral from "@babel/runtime/helpers/taggedTemplateLiteral";
import _typeof from "@babel/runtime/helpers/typeof";
```

Essentially these boil down to functions which are needed for older browsers like Edge 18, but not browsers which GitHub officially supports:

 - Object spread (`_objectSpread`, `_objectWithoutProperties`). These work across all modern browsers, but aren't supported in Edge 18 and below, which is not officially supported by GitHub 
image
 
`Object.assign` (`_extends`) works in Edge 12 and above. No issues here.
image

 - Class helpers (`_createClass`, `_defineProperty`, `_classCallCheck`) which are supported by Edge 13+ 
image

 - Async generators (`_asyncToGenerator`) which is supported by all modern browsers, but not Edge 18 or below, which is not officially supported by GitHub.
image

The list continues... but ultimately each of these runtime functions is to patch behaviour in unsupported browsers. By dropping the runtime transform we can significantly reduces the build size, from 159k to 147k with no other impacts to modern browsers.

### CODE REVIEW

**Review by emplums — COMMENTED** [review]
Looks good to me! I will let @BinaryMuse get a chance to look over as well before merging :)

**Comment by keithamus** [comment]
Ah it looks like dropping `preset-env` may have caused test failures because ESM syntax isn't getting compiled.

**Comment by BinaryMuse** [comment]
Awesome, thanks for picking this up @keithamus! I'm definitely for this PR in spirit; I'd just want to (1) get the tests working (of course) and (2) possibly update the docs to make sure we list the features you might want to po[nl]yfill if you're not GitHub. Happy to pick this up and get it across the finish line but it might be a few days before I can give it a lot of attention.

**Comment by keithamus** [comment]
I'll get the tests passing tomorrow and add some documentation about what to polyfill.

**Comment by keithamus** [comment]
I've updated docs to add a section in the Getting Started guide. It does not prescribe exact polyfills/transforms as this might be a bit tricky to keep up to date, but it enumerates the browsers we support and suggests that syntax transforms will be needed for Edge 18 support.

**Review by emplums — APPROVED** [review]
Looks good! I'm going to move this into the release branch and change that release to be a major release since this is technically a breaking change 👍

**Pull request merged**
