### PR TITLE
Deprecation testing and zero runtime cost in prod

### PR DESCRIPTION
**Pull request by BinaryMuse**
This PR builds on the Babel and compilation changes in #789 and @emplums' deprecation work in #777. It adds the following features:

* a `useDeprecation` hook that ensures we only log a deprecation warning to the console once if a component re-renders. For example:

    ```javascript
    const Flash = ({variant, scheme, ...props}) => {
      const deprecate = useDeprecation({
        name: 'Flash "scheme" prop',
        version: '20.0.0',
        message: 'Use the variant prop instead. See https://primer.style/components/Flash for more details.'
      })

      if (scheme) {
        deprecate()
        variant = schemeMap[scheme]
      }

      return <StyledFlash variant={variant} {...props} />
    }
    ```

* the ability to test for deprecations, e.g.:

    ```javascript
    it('respects the deprecated "scheme" prop', () => {
      expect(render(<Flash scheme="green" theme={theme} />)).toHaveStyleRule('background-color', colors.green[1])
      expect(Deprecations.getDeprecations()).toHaveLength(1)
    })
    ```

* a global test to ensure we're not shipping deprecated code that we meant to be removed:

    ```javascript
    import semver from 'semver'
    import {Deprecations} from '../utils/deprecate'

    const ourVersion = require('../../package.json').version

    beforeEach(() => {
      Deprecations.clearDeprecations()
    })

    afterEach(() => {
      const deprecations = Deprecations.getDeprecations()

      for (const dep of deprecations) {
        if (semver.gte(ourVersion, dep.version)) {
          throw new Error(`Found a deprecation that should be removed in ${dep.version}`)
        }
      }
    })
    ```

* zero runtime overhead in production

    All the deprecation code is wrapped in `if (__DEV__)`, which gets compiled to `if (process.env.NODE_ENV !== "production")`. When a user bundles their code and sets `NODE_ENV` to `"production"`, this changes to `if (false)` and minifiers will remove the entire function block

### CODE REVIEW

**Comment by BinaryMuse** [comment]
Since each deprecation has a `name` property, we could also modify the system to only warn once per deprecation *type* instead of deprecation *instance*. However, it may be useful to be notified if you're using the same deprecated code in multiple places in your codebase. [Grim](https://www.npmjs.com/package/grim) reports once *per source code location* by generating and storing some stack frames.

**Comment by BinaryMuse** [comment]
@emplums We currently don't have any docs relating to using Primer Components with a module bundler. It's standard practice (at least in React apps) to compile using `NODE_ENV="production"` because it pulls out a ton of dev-mode stuff from React, but we could always add a doc on bundling.

**Comment by emplums** [comment]
@BinaryMuse I think a small note in `Getting Started` just saying something like "If you'd like deprecation warnings not to appear in production, make sure you've got `NODE_ENV="production"` set in your bundler.

**Comment by BinaryMuse** [comment]
Merging this down to the base PR

**Pull request merged**
