### PR TITLE
The Great Typescript Refactor

### PR DESCRIPTION
**Pull request by BinaryMuse**
It's happening!

This PR introduces a ~rewrite~ refactor of Primer Components into TypeScript.

We've discussed moving to TypeScript for a while now; I won't spend time discussing rationale here, but given the bugs we've had in the past around our (manually-created) typings as Primer Components has grown, and given the increasing number of TypeScript projects using PC, I believe it is well past time we made this change.

One issue with moving to TypeScript is that we want to keep `propTypes`; React prop types are for runtime, dev-mode checking of passed types, whereas TypeScript is only used at compile time. In order for us to keep both and not have to continue to maintain a set of `propTypes` as well as a set of TS interfaces, we need a way to infer one of those from the other.

Thankfully, the PropTypes package exposes a type called `InferProps`, which creates a TypeScript type out of a set of existing `propTypes`. The major challenge here is that we make heavy use of `@styled-system/prop-types`, which does not have an associated `@types` package.

For this reason, this PR includes a new script, `script/create-css-prop-types.ts`, which will iterate through the styled-system prop categories and create a `.d.ts` file that we can include in the project. This file gets checked in as `src/styled-system__prop-types.d.ts`.

Combined with some TS hackery in `constants.ts`, we have all the pieces we need to generate appropriate types. Here's an example of converting a JS component into a TS one:

**Before (JS)**:

```js
const Box = styled.div`
  ${COMMON}
  ${FLEX}
  ${LAYOUT}
  ${sx};
`

Box.defaultProps = {theme}

Box.propTypes = {
  ...COMMON.propTypes,
  ...FLEX.propTypes,
  ...LAYOUT.propTypes,
  ...sx.propTypes,
  theme: PropTypes.object
}

export default Box
```

**After (TS)**:

```typescript
const boxPropTypes = {
  ...COMMON.propTypes,
  ...FLEX.propTypes,
  ...LAYOUT.propTypes,
  ...sxPropTypes,
  theme: PropTypes.object
}

export type BoxProps = PropTypes.InferProps<typeof boxPropTypes>

const Box: React.FC<BoxProps> = styled.div`
  ${COMMON}
  ${FLEX}
  ${LAYOUT}
  ${sx};
`

Box.defaultProps = { theme }

Box.propTypes = boxPropTypes

export default Box
```

This PR also updates Jest settings for testing TS files (and eventually writing tests in TS), and updates the Gatsby config in the `docs/` folder to ensure that live editing of docs and components still works.

### CODE REVIEW

**Comment by emplums** [comment]
@BinaryMuse so excited for this! I have one question that I've been mulling over - does this approach limit the kinds of types we can use of our components to the constraints of the `React.propTypes` API? Are there things that we can do in TS that we can't do using `React.propTypes`? Will you have any recommendations for writing good prop types that will be easily translated to TS?

**Comment by BinaryMuse** [comment]
> does this approach limit the kinds of types we can use in our components to the constraints of the `React.propTypes` API?

I'm still exploring but from what I can tell, `InferProps` handles most of the basic cases. For situations where we want additional information in our TS types (aka, we actually want the TS types to diverge from propTypes), we can do our own thing. For example, here's a change to `Box.tsx` that typechecks:

```diff
diff --git a/src/Box.tsx b/src/Box.tsx
index 58e71ca4..a8ff783c 100644
--- a/src/Box.tsx
+++ b/src/Box.tsx
@@ -10,10 +10,15 @@ const boxPropTypes = {
   ...FLEX.propTypes,
   ...LAYOUT.propTypes,
   ...sxPropTypes,
+  onClick: PropTypes.func,
   theme: PropTypes.object
 }
 
-export type BoxProps = PropTypes.InferProps<typeof boxPropTypes>
+export type BoxProps = Omit<PropTypes.InferProps<typeof boxPropTypes>, "onClick">
+  & {
+    onClick?: (event: React.MouseEvent<HTMLDivElement, MouseEvent>) => void
+  }
 
 const Box: React.FC<BoxProps> = styled.div`
   ${COMMON}
@@ -22,6 +27,8 @@ const Box: React.FC<BoxProps> = styled.div`
   ${sx};
 `
 
+const b = <Box onClick={true} />
+
 Box.defaultProps = { theme }
 
 Box.propTypes = boxPropTypes
```

image

**Comment by BinaryMuse** [comment]
> I guess my worry is that we are obscuring using actual TS too much by compiling the types from our prop types and that could lead to unintentionally compiling the wrong types

I think this is a reasonable worry, but given how seldom we actually do anything fancy with the TS types, I believe it will be far easier to deal with `InferProps` and handle edge cases ourselves.

Also, similar to the way I manually typed the styled-system propTypes, we can create our own propTypes that have both runtime checking *and* inferable TS types.

**Comment by emplums** [comment]
> given how seldom we actually do anything fancy with the TS types, I believe it will be far easier to deal with InferProps and handle edge cases ourselves.
I agree! I think we should continue forward with this approach, only thing I think we'll need to make sure we have before shipping is some way to know if `InferTypes` is working as we expect it to before shipping changes + maybe some Do's & Dont's for folks around what kinds of things will get translated fine by `InferTypes` and what things won't. My worry is that right not it's not super clear what output you're going to get from `InferTypes` unless you manually spot check in the file like you did in your example. Would you be able to hover over the component declaration to see what `InferTypes` outputs?

**Comment by BinaryMuse** [comment]
One thing to add: I think the name `InferProps` is a little misleading; it [uses the TypeScript type inference](https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-inference-in-conditional-types) but the actual prop types themselves are strongly typed.

**Comment by emplums** [comment]
> So, as long as you know the associated propType has the correct PropTypes.Requirable<T> or PropTypes.Validator<T> type attached, you should be good to go.
How would you check this? Do all values on the `React.propTypes` object have these?

**Comment by emplums** [comment]
> Similarly, one can use the same mechanism for building your own more complex propTypes with more detailed TS types that infer correctly. For example:
> 
> type MouseEventHandler<T> = (event: React.MouseEvent<T, MouseEvent>) => void
> // a more specific PropTypes.func; only difference is the associated type
> const divClickHandlerPropType = PropTypes.func as PropTypes.Requireable<MouseEventHandler<HTMLDivElement>>

This is awesomeeeeee 😻

**Comment by BinaryMuse** [comment]
> How would you check this? Do all values on the `React.propTypes` object have these?

Yes, all the built-in prop types from `@types/prop-types` have TS types that work as you'd expect them to work given how they work at runtime in JS

**Comment by colebemis** [comment]
Closing in favor of https://github.com/primer/components/pull/959

**Pull request closed without merging**
