### PR TITLE
Make raw.macro a normal dependency

### PR DESCRIPTION
**Pull request by rafeca**
This PR changes the `raw.macro` dependency (which was introduced in https://github.com/primer/components/pull/489) to be a normal dependency.

Even if this `npm` package is used for build purposes, it needs to get installed when installing `@primer/components` in order to make `babel` build correctly the `Dialog` component.

If this is not the right approach, maybe it would be good to add a mention about installing `raw.macro` on the project Readme.

#### Merge checklist

None of this checks are applicable:

- [x] Changed base branch to release branch
- [x] Add or update TypeScript definitions (`index.d.ts`) if necessary
- [x] Tested in Chrome
- [x] Tested in Firefox
- [x] Tested in Safari
- [x] Tested in Edge

### CODE REVIEW

**Comment by colebemis** [comment]
Thanks for the PR, @rafeca! 😸 

Are you seeing an error message related to `raw.macro`?

I ask because users shouldn't have to know about `raw.macro`. It's an implementation detail. In fact, user shouldn't have to worry about compiling `@primer/components` with Babel at all. We compile the code with Babel before publishing to npm. All usages of `raw.macro` (e.g. `raw()`) are replaced with strings at build time, before the package is published. I looked through the 13.2.0 build files and couldn't find any references to `raw.macro`. The one place we use `raw()` was replaced by a string: https://unpkg.com/browse/@primer/components@13.2.0/dist/index.esm.js#L861

**Comment by colebemis** [comment]
@rafeca How are you importing the `Dialog` component?

**Comment by rafeca** [comment]
Hey @colebemis ! Thanks for the quick response! We're importing the components directly from the `src` folder (e.g `import Dialog from "@primer/components/src/Dialog";`, so I guess that's not the right way to import them...

We should import them directly from `@primer/components` to get the transformed ones, but then to avoid including all unused components we have to rely on the bundler doing proper tree shaking (which I guess it's fine).

Anyways, this PR is not relevant 😅

**Comment by emplums** [comment]
Hey @rafeca! We built it to assume that tree shaking would be set up properly in the consumers application, but we are looking into exporting a bundle for each component to make this a bit easier on consumers!

**Pull request closed without merging**
